site_name: Projeto Backend 2025-1 V
repo_url: https://github.com/Projetos-de-Extensao/PBE_25.1_8001_V_Mbappython

nav:
  - Home: index.md
  - Tutorial de Uso: tutorial.md
  - API: api.md
  - Instalação:
    - Backend: instalacao_backend.md
    - Frontend: instalacao_frontend.md
  - Técnico:
    - Arquitetura: arquitetura.md
    - Segurança: seguranca.md
    - Configurações: configuracoes.md
    - Releases: releases.md
  - FAQ: faq.md
  - Equipe: equipe.md
  - Contribuir: contribuir.md
  - Documentação:
    - Iniciação:
      - _Iniciação/documento_de_visao.md
      - _Iniciação/requisitos.md
      - _Iniciação/5w2h.md
      - _Iniciação/Brainstorm.md
      - _Iniciação/mapa_mental.md
      - _Iniciação/metodologia.md
      - _Iniciação/pesquisa.md
      - _Iniciação/prototipo_alta_fidelidade.md
      - _Iniciação/entrevista.md
    - Elaboração:
      - Modelagem: 
        - __Elaboração/modelagem/index.md
        - Diagrama de Classes: __Elaboração/modelagem/diagrama_de_classes.md
        - Diagrama de Análise de Sistema: __Elaboração/modelagem/das.md
    - Construção: ___Construção/index.md
    - Transição: ____Transição/index.md
    - Iteração: _____Iteração/interacao1.md

theme:
  name: material
  palette:
    primary: default
  color_mode: dark
  language: pt-BR
  user_color_mode_toggle: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select
    - content.code.annotate 

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true
      include_source: true

extra:
  consent:
    actions:
      - accept
      - manage

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true