# Generated by Django 4.2.20 on 2025-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_administrador_cliente_endereco_notificacao_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='senha',
            field=models.CharField(default='senha123', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='senha123', max_length=255),
        ),
        migrations.AddField(
            model_name='operador',
            name='senha',
            field=models.CharField(default='senha123', max_length=255),
        ),
    ]
