# Generated by Django 4.2.20 on 2025-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_administrador_senha_cliente_senha_operador_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('SOL', 'Solicitado'), ('AC', 'Aguardando Confirmação'), ('CE', 'Cotação enviada'), ('PA', 'Pagamento Aprovados'), ('AND', 'Em Andamento'), ('ENT', 'Entregue'), ('CAN', 'Cancelado')], default='SOL', max_length=3),
        ),
    ]
