# Generated by Django 4.2.20 on 2025-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosolicitado',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
