# Generated by Django 4.2.20 on 2025-05-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pedido_preco_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entrega_efetiva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
