# Generated by Django 5.2 on 2025-05-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pedido_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entrega_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
